Real-Dev-Squad/website-www

css/events.css
This PR solves issue #203.
After investigating the logo in developer tools, the computed height is 400px. I matched the width to the computed height and then made the computed height explicit by including it in the `logo-img` class.
=> Changed logo width to 400px to match height. Made height explicit.

css/navbar.css, index.html
#219 issue is resolve
-Done the styling of Github sign in button
-Make the text and logo in one line
-  Yes
Before :
After :
mobile view :
=> style: btn-login-text updated

js/index.js, package-lock.json, package.json
The member image URL's had varying sizes, so I added some preprocessing to the URL string that adds the following ensures a 200x200 dimension picture like so:
`res.cloudinary.com/realdevsquad/image/upload/w_200,h_200/v1645293071/profile/XAF7rSUvk4p0d098qWYS/ovew4w7n6zdmgy03yr3z.png`
N/A
=> added standardized image sizing to member images

css/navbar.css
Closes #362 
- removed padding property in dropdown-item css class.
- changed some styling in dropdown-link class
After :
=> changed dropdown item css

app/components/stepper.js, app/controllers/join.js, tests/unit/controllers/join-test.js
1. `app/controllers/join.js` : This file contains the controller for the join route.
2. `app/components/stepper.js` : Add the query params to the stepper component.
3. `tests/unit/controllers/join-test.js` : Add the test for the join controller.
- First we check `join` controller is exist or not.
- Second we check `join` controller has expected the query params `step`.
https://user-images.githubusercontent.com/70854507/221082334-f5cf8095-f83a-42db-848a-fd36e37900a3.mp4
**Note:** We skip the test for the stepper component.
=> add query param for join steps

events.html
For a better user experience, we have added `year` as well along with the date of event. Earlier `year` was missing which can lead confusion to user considering the edge case where there are events with same date but with different years.
=> feat: add year in event card

app/components/reusables/onboarding-input.hbs, app/components/signup-steps/step-one.hbs, app/components/signup-steps/step-one.js, app/components/stepper-signup.js, app/constants/stepper-signup-data.js, app/styles/onboarding-card.module.css, app/styles/stepper.module.css, tests/integration/components/signup-steps/step-one-test.js
Parent Ticket: https://github.com/Real-Dev-Squad/todo-action-items/issues/178
- Added a role selection feature on the signup-details page using a select tag, allowing users to choose a single role.
- The selected role is now passed to the signupDetails object in stepper-signup.js.
- Ensured that only one role is stored in signupDetails.role at a time.
- Added test render select your role dropdown on signup details page and update signupdetails.role object
- Feature under feature flag
Button part handle in this pr: https://github.com/Real-Dev-Squad/website-www/issues/651
https://github.com/Real-Dev-Squad/website-www/assets/107163260/ae462ed5-4301-46c7-9e75-9dd600d23774
=> [Onboarding Flow]- Add role option for a user on signup detail page

app/components/reusables/onboarding-input.hbs, app/components/signup-steps/step-one.hbs, app/components/signup-steps/step-one.js, app/constants/toast-notification.js, app/styles/onboarding-card.module.css, tests/integration/components/signup-steps/step-one-test.js
Parent ticket: https://github.com/Real-Dev-Squad/todo-action-items/issues/178
- Allow user to input anything in "firstname" and "lastname" input field
- If the input in the "firstname" or "lastname" fields violates certain criteria i.e. input not contain spaces, non-alphabetical characters, numbers, more than 20 character, an error message should be displayed below the respective input field ("firstname" and "lastname") and generateusername button will disable
-  If the input in both the "firstname" and "lastname" fields meet the criteria, a button will enable and a username should be generated.
- When the "sign-in-with-github" session is logged out, and the "generateUsername" button is clicked, A toast message should be displayed.
- Feature under feature flag …
=> User Signup Form Validation and Toast Message

app/components/signup-steps/step-one.hbs, app/components/signup-steps/step-one.js, app/components/signup-steps/step-two.hbs, app/components/signup-steps/step-two.js, app/components/stepper-signup.hbs, app/components/stepper-signup.js, app/styles/onboarding-card.module.css, tests/integration/components/signup-steps/step-one-test.js, tests/integration/components/signup-steps/step-two-test.js
parent ticket: https://github.com/Real-Dev-Squad/todo-action-items/issues/178
- When user choose role role `maven` then checkbox with label render  on signupdetails page
- When user choose role `developer` then step-2 page render with different description + button with text 'let's go'
- When user choose role `maven`, `product manager`, `designer` then step-2 page render with different description + button with text 'Join Our Discord'
- When user click signup button then role stored in local storage because step-2 page render depend on role and if we not stored in local storage then when we refresh our step-2 page then else condition page get render.
- Added rds logo on all onboarding card
- feature under feature flag
https://github.com/Real-Dev-Squad/website-www/assets/107163260/68203243- …
=> [Onboarding Flow]-Signup Process for Different User Roles 

app/components/live-participants.hbs, app/components/live-participants.js, tests/integration/components/live-participants-test.js
- Closes #680 
There should be user statistics that should give information about the number of participants for each role joining the stream.
https://github.com/Real-Dev-Squad/website-www/assets/82165483/6314a32c-00f6-494e-b290-a05c3b5c2918
https://github.com/Real-Dev-Squad/website-www/assets/82165483/00dd130c-2124-46ce-9c66-6fdf8599a6b3
=> [Live-site] - Show Count of Users Joined

app/components/live-participants.hbs, tests/integration/components/live-participants-test.js
- Remove the kick-out option for the host as the host cannot kick out hosts in the event.
https://github.com/Real-Dev-Squad/website-www/assets/40385118/45fa7e75-b843-4b41-bbd1-cd1b650c7d9f
Moderator:
=> [Live Site]: Remove kick out option for host

app/components/footer.hbs, app/components/footer.js, tests/acceptance/render-footer-dynamically-test.js
closes #722 
- #722 
- This change dynamically renders footer depending on route. Only `The contents of this website are deployed from this open sourced repo` part is visible in all pages and in home route events and other parts of footer is visible.
https://github.com/Real-Dev-Squad/website-www/assets/87164140/388022d0-a8dd-4051-8daf-9c233a15357d
https://github.com/Real-Dev-Squad/website-www/assets/87164140/e1a08462-c727-41e2-a013-4b23d5df3306
=> [Ember-Migration] Footer Enhancement

app/services/live.js
In this PR I have fixed the issue screen share text not updating when screen share stops for joined peers.
- Updated the tracked variable so that rendering happens accordingly.
Date: 6-11-2023
Developer Name: Satyam Bajpai
PR Number(s):- #737
Issue Ticket Number:- #736 
Backend changes
Frontend Changes
Is Under Feature Flag 
Deployment notes
Any special instructions for the deployment (N/A)
Tested in staging
https://github.com/Real-Dev-Squad/website-www/assets/85296770/74f1c929-09c7-48ed-8a7d-8388823e1666
**Note :**
- Delete the description below headings `What is the change?` & …
=> fix: screen share text update issue

.stylelintignore, app/components/footer.hbs, tests/acceptance/render-footer-dynamically-test.js, tests/integration/components/events-test.js, tests/integration/components/footer-test.js
Hides events links, will show them after migration to ember is done
=> Hide home events links

app/controllers/live.js
Date: `24-01-2024`
---
- #849 
Currently in the word cloud question answer feature a modal appears automatically even if the host hasn't asked a question. The modal appears with a empty question at some small intervals which is not a good UI/UX, and it is not supposed to work like that.
=> fix: modal opening issue even if host doesn't asks questions

app/components/join-section.hbs, app/components/stepper.js, app/controllers/live.js, tests/integration/components/live-join-test.js
Date: `27-02-2024`
---
- #875 
This is a develop to main PR.
> Staging Working Proof
=> Sync: Dev to main

app/components/stepper.js
Date: 28-03-2024
Developer Name: Satyam Bajpai
---
-  #882
Removed the join form submit restriction by uncommenting the code.
=> fix: join form submit restriction

app/services/login.js, ember-cli-build.js, fastboot/initializers/ajax.js, tests/unit/services/login-test.js
Date: `13-06-2024`
---
- #888 
In this PR I have configured server side rendering in the web app.
> Before
> After
=> feat: configure server side rendering in the app

app/constants/application.js, app/controllers/intro.js, app/templates/intro.hbs, app/utils/validate-application-details.js
Date: 18th August 2024
Developer Name: yash raj
- #906 
- #900 
- integrate the patch API to approve / reject a application.
=> integrate api to approve / reject a application

app/constants/apis.js, app/routes/intro.js, tests/integration/components/status-card-test.js
- #903
In this pr the personalized link consists of the query ?status=submitted and when the super user visits the link it will redirect them to dashboard site for the particular application
=> Redirection to dashboard user application on /intro route

app/constants/apis.js, app/routes/intro.js
The PR is related to the changes made to the `IntroRoute` component to handle the scenario where a superuser should be redirected if the `redirect` query parameter is not `'false'` and if there is not query params.
=> Fix redirection for super user 

README.md
Date: `20/08/2024`
Developer Name: `Akanksha Dharkar`
---
Not applicable
While setting up the repo, I realised that the readme says to use `npm i` but the file in the repo is yarn.lock
Not required here
=> README updation: use yarn instead of npm

app/controllers/join.js, app/services/onboarding.js, app/templates/join.hbs
- closes #911 
navigating to the /join route, it fetch the users application details if exist redirect them to the status card of the application otherwise let them filled the application
=> fix status card rendering based on user application

app/routes/intro.js
- closes #920 
When normal users visit /intro route then they will redirect to /join to check their application status
=> Fix users routing on /intro 

app/components/stepper-signup.hbs, app/components/stepper-signup.js, app/components/stepper.hbs, app/components/stepper.js, app/controllers/join.js, app/templates/join.hbs, tests/integration/components/status-card-test.js
- closes #926 
fix this discord join button now by clicking the button should redirect the user to the Discord server invitation.
https://github.com/user-attachments/assets/7850950f-a7b2-458f-a332-5cd04c259ffb
=> Fix join discord button

app/components/debug-grids.hbs, app/components/debug-grids.js, app/routes/debug.js, tests/integration/components/debug-grids-test.js, tests/unit/routes/debug-test.js
Date: `13-09-2024`
Developer Name: `Shubham Raj`
---
- Closes #907 
This PR remove page /debug from the feature flag, and makes the feature fully functional
- 
rather remove this page from the dev feature flag
development environment tested using with the staging data 
on toggle roles super_user changes to false
[Screencast from 18-09-24 04:41:47 AM IST.webm](https://github.com/user-attachments/assets/5cc1b4d3-c89e-4a06-ad96-615e43d789fe)
test coverage for toggle button's functionality
test coverage for removing the page from the feature flag
=> [feat] Toggle Super_user privileges

app/components/header.hbs, app/components/join-section.hbs, app/constants/regex.js, app/controllers/subscribe.js, app/styles/join-section.module.css, app/styles/subscribe.module.css, app/templates/subscribe.hbs
Date: 22 oct, 2024
---
- [link](https://github.com/Real-Dev-Squad/website-backend/issues/2123)
- this PR I have made changes asked by @ankushdharkar 
1. First is the remove subscription link from the navbar.
2. Make the input box text black(different from placeholder)
3. match phone number regex from the backend.
- [] No
https://github.com/user-attachments/assets/00fbcb99-2836-4924-a2db-d0b104205f77
**Tests for this feature are in this PR: #945**
=> subscription feature fixes

app/controllers/subscribe.js
Date: 24 oct, 2024
---
closes https://github.com/Real-Dev-Squad/website-backend/issues/2228
The issue is we were using phone in "KEYS_NOT_ALLOWED" but while taking user phone inputs we took phoneNumber as field, which exposed phone number publicly. So, in this PR we are fixing the issue motioned above.
- Next we will merge this stacked PR
https://github.com/Real-Dev-Squad/website-www/pull/945
=> [HOT FIX] change phonNumber to phone to hide from user/self API

app/adapters/user.js, app/components/debug-grids.js, app/controllers/goto.js, app/routes/intro.js, app/services/login.js
Date: 08 Dec 2024
Developer Name: Hariom Vashista
---
Fixes: Real-Dev-Squad/todo-action-items#255 repo#2
This PR aims at updating the deprecating API endpoint from /users/self to /users?profile=true
The tests was failing in the previous PR i opened for this same issue for some reason https://github.com/Real-Dev-Squad/website-www/pull/959. Creating a new PR for this reason. Below is the screenshot for the integration test result now:
=> Updated deprecated API endpoint from /users/self to /users?profile=true

app/constants/urls.js, app/controllers/discord.js, app/router.js, app/routes/discord.js, app/templates/disocrd.hbs, app/utils/redirect-auth.js, tests/unit/routes/discord-test.js
Date: 17 January, 2025
Developer Name: [Tejasgp](@tejaskh3 )
This PR introduces the integration of Discord account linking functionality. The following updates have been made:
- Tracks the Discord ID and linking status.  
- Provides user feedback through toast notifications.  
- Implements consent handling before linking the Discord account.  
- Handles API responses for linking, including token expiration and errors.  
- https://github.com/Real-Dev-Squad/website-www/issues/592
- Add UI design and logic to `discord.hbs` in future PRs.
- and test cases for the same
---
---
---
---
=> [My Site Migration] feat: add discord route

app/components/spinner.hbs, app/styles/app.css
Date: 22-03-2025
---
- Closes #1007
The PR fixes the styling issue while rendering the loader. An extra spinner class was added in `spinner.hbs`, leading to multiple loaders on `/status`, `/identity`, `/profile` pages.
<details>
<summary>Screen recording</summary>
https://github.com/user-attachments/assets/fa2deeaf-c76d-45a6-bed5-c647884185ff
https://github.com/user-attachments/assets/f180ec56-c344-4100-ace7-3e4cb4eead01
</details>
<details>
<summary>Screencast for Mobile</summary>
https://github.com/user-attachments/assets/0e6ccdd1-55a8-4e0a-ba28-3a83301a2933
</details>
<details> …
=> fix: styling issue in rendering loader

tests/constants/users-data.js, tests/unit/controllers/new-signup-test.js
Date: 21-04-2025
---
- #1021 
(Doesn't close the issue)
- New-Signup page is being migrated from `my-site` to `main-site`.
- The PR contains unit tests for the new-signup controller moved in #1039
- New Signup page is under dev flag and using another signupDev flag to switch between new and old signup method.
The PR contains unit tests for new-signup controller and below are ss for ones added and local working proof
=> [My Site Migration] new-signup page (controller-unit-tests) 

tests/constants/users-data.js, tests/unit/controllers/new-signup-test.js
Date: 21-04-2025
---
- #1021 
(Doesn't close the issue)
- This PR overlaps with PR #1037 and refer to that for comments and reviews. This PR merges unit tests in the develop branch, which were previously wrongly merged in the feat branch.
- New-Signup page is being migrated from `my-site` to `main-site`.
- The PR contains unit tests for the new-signup controller moved in #1039
- New Signup page is under dev flag and using another signupDev flag to switch between new and old signup method.
Refer to #1037 for previous reviews.
The PR contains unit tests for new-signup controller and …
=> [My Site Migration] new-signup page (controller-unit-tests)

app/components/identity/reload.hbs, app/controllers/identity.js, app/routes/identity.js, app/styles/identity.module.css, app/templates/identity.hbs, tests/unit/controllers/identity-test.js
Date: 14-05-25
---
- Closes #1051 
- This PR fixes a bug during identity page reload where user with blocked status were displayed Get-Started Page instead of Status Blocked
https://github.com/user-attachments/assets/9207870e-a767-4c6f-96f6-af1d93685402
https://github.com/user-attachments/assets/9d2168db-4400-496e-8c73-aca808b0cacd
=> Fix identity page reload

app/controllers/new-signup.js
Date: 16-05-2025
---
- Closes #1055
- Fixes a bug where even after successful user signup, the last step doesn't show up due to a missing `return` statement in response
- No test changes required as this helper function was missing a return response for promise and was being mocked in controller unit tests to resolve for particular success/failure response.
- N/A
https://github.com/user-attachments/assets/313087b5-b75e-4088-8b8d-a31244801c4c
(Note:- 6 tests were already skipped in the repo)
=> fix: change to last step after successful signup

app/routes/join.js, tests/acceptance/render-footer-dynamically-test.js
Date: 11 June, 2024
---
https://github.com/Real-Dev-Squad/website-www/issues/1064
- In this PR, we are making `/join` route publicly available, but hiding the steps to go there(this was already done)
Breaking changes (If your feature is breaking/missing something, please mention pending tickets)
=> fix: make join publicly available
