css/events.css, events.html
=> Events info update

css/events.css, events.html
=> WEB-10 Event page visuals

css/events.css, css/main.css, events.html
=> WEB-12 Added event link on events page

css/main.css, index.html
=> Adding text for current events and linking to /events

css/main.css
=> CSS fix for WEB-28

events.html
Added my topic for July 12 event
=> event data update - satyam bansal

index.html
Please let me know if any changes need to be done! I also feel we should add discord link too.
=> added social media handles

event-react-hooks-july-2020.html, event-ssr-correctly-august-2020.html, event-web-mini-conf-july-2020.html, index.html
=> Added SSR Event happening

event-dynamic-programming-october-2020.html, event-nodejs-workshop-october-2020.html, event-react-hooks-july-2020.html, event-web-mini-conf-july-2020.html, index.html
Added new events to website. 
Removed the outdated information.
Linked the members page in the footer where necessary. Fixes #59
=> Updated the content on website. (www.realdevsquad.com)

css/main.css, index.html
This area will be useful to show some of the new things happening across our sites
=> Added a showcase area for new updates and notifications

index.html
Added the bare minimum og tags to make the site look better for sharing previews
=> ISSUE-68 Added OG information for better sharing previews

css/user-form.css, js/user-form.js, user-form.html
Additions:-
1. HTML form to populate logged in user data. 
2. Styling in vanilla CSS.
3. *Validating input fields using JavaScript.
Impending:-
1. Making the form responsive.
2. Populate user data
3. PATCH details & submit to the server
=> User profile information form #54 [WIP]

css/navbar.css, events.html, index.html
**Next phase** - Responsiveness for mobile screens
=> Adding navbar on home-page and events-page

css/user-form.css, js/user-form.js, user-form.html
The user profile picture will come from the website-static repo. We will use the username as the key for selecting the profile image
Closes #72
=> Disabled user profile image in input

css/main.css
Top margin added to the sign in button (see screenshot). Solution to the issue #83 
**Screen Shot**
=> sign in button top margin added

js/main.js
Post Github signup user will be redirected to the Signup form to fill in further details.
=> Ref(index.html): redirection added to signup form

css/main.css, css/navbar.css, index.html, releases.html
=> One year anniversary page changes

README.md
Updated README.md with pre-commit hook details
=> Adds notes regarding the pre-commit hooks in README.md

event-APIs-made-Easier-April-2021.html, events.html
=> Removed references to EmberJS Site from navbars from all files(2 files)

js/goto.js
The new signup page expects a query param - state
ref - [PR](https://github.com/Real-Dev-Squad/website-my/pull/78)
=> Add query param for signup page

css/main.css
Issue- Update the styling of the links according to ambiance of the web page.
Changes made -  Made changes in main.css. Changed colour of links to pink and removed underline.
(After making changes, looking like this) #100
=> Updated styling of links

CONTRIBUTE.md
Updated CONTRIBUTE.md by adding contents of the image as text
Issue #122
=> Added CONTRIBUTE.md file

CONTRIBUTE.md
Update contribute.md file #131
Before
`website-my`
After
`website-www`
=> Updated Contribute.md File

css/animate.css, css/main.css, index.html, js/animate.js, js/main.js
This is how it looks => https://youtu.be/LU3ett-Ef_Y
=> Members Photo Animation #124

css/main.css, index.html, js/animate.js, js/main.js, package-lock.json
A skeleton loader will appear now while the images load.  Please look at the video attached for more clarity. (#125) 
- Before: 
https://youtu.be/LU3ett-Ef_Y
- After
https://user-images.githubusercontent.com/61474917/124365383-4907fd00-dc65-11eb-9ecd-fbe3f1c9344d.mp4
=> Added a shimmer UI Effect.

.github/workflows/percy.yml, .prettierrc.json, CONTRIBUTE.md, css/animate.css, css/main.css, css/user-form.css, event-APIs-made-Easier-April-2021.html, events.html, goto.html, index.html, js/animate.js, js/goto.js, js/main.js, package-lock.json, releases.html
Changes : 
1.) Removed references to EmberJS Site from navbars from all files.
2.) Add query param for signup page.
=> Merging changes from the develop branch to the main branch.

css/main.css, index.html, package-lock.json
=> Adding the content about our community

art-feature.html, css/main.css, index.html, js/artFeature.js, package-lock.json
closes #116 
Example output :-
=> Art Creator Feature 

css/main.css
Fixed content alignment for different screen sizes.
=> Fixed content for main branch

css/main.css
Attaching the images for reference
=>   Fix the content margin/padding #176 

index.html
=> Removed the linked page in art-feature

css/main.css, css/navbar.css, events.html, releases.html
Closes #183 
Desktop View :
Mobile View :
=> fixed broken css of `releases.html`

css/navbar.css, events.html, index.html, js/artFeature.js, package-lock.json, releases.html
Closes #162 
1. Added link to redirect user to `https://my.realdevsquad.com/profile` page on clicking `Hello, user-name`
2. Replaced `realdevsquad.com` with `www.realdevsquad.com` in `events.html` and `releases.html` files
3. Fixed `https://crypto.realdevsquad.com/auction` link
=> fix: navigation to user profile page

event-APIs-made-Easier-April-2021.html, index.html
1 - Fixed some broken links
2 - Refactored CSS of Upcoming Events
=> Fixed attached links and refactored html

.github/Pull_Request_Template.md, README.md, css/events.css, css/main.css
Closes #197 
- Fixed font of footer
- Added padding on event links, therefore on hover, the background has some padding.
- Fixed font of speaker info in `events page`  to make it readable
After :
1. ![image](https://user-images.githubusercontent.com/35677839/148340332-21244859-0663-4cc9-9699-f5ffae45257e.png)
2. ![image](https://user-images.githubusercontent.com/35677839/148340464-9ca52431-01ae-4ff9-b2bb-8ef718c8ea59.png)
=> fix: minor css changes

css/main.css, index.html
This issue was occuring because, there was no height assigned to the image, I gave the image a height as well as wrapped it in a container.
- added `height` property to the image
- added `overflow-anchor: none;` and `z-index: 1;` to the image for further diminishing the issue.
Before: 
https://user-images.githubusercontent.com/52736997/148355615-1b71dc80-2b7c-44b1-9a68-2577af03541b.mp4
After:
=> Fixed layout shift issue on reload

index.html
Closes #222 
Updated the image url under meta for following elements:
* og:image URL
* twitter:image URL
=> Fixed (og: image & twitter:image)URL

.vscode/settings.json, js/github.js, js/index.js, js/user.js
Closes #233 
Adds VF flow
- [✅ ] Yes
=> feature(I-233): Added VF flow

.vscode/settings.json, js/github.js, js/index.js, js/user.js
=> feature(I-233): Added VF flow (#234)

css/main.css, index.html, package-lock.json
#31 Drop-in input field for collecting emails 
Made the Email subscription form.
DONE THIS
=> Made the email capture form on the homepage

css/main.css, index.html
=> added fix to open cards upon clicking and moved the Close button to right.

css/navbar.css
**Issue**
Closes [#249 ](https://github.com/Real-Dev-Squad/website-www/issues/248)
**What is the change?**
Changed Color for Navbar in Dark-Mode [Mobile View]
=> Updated line 126 of navbar.css

css/navbar.css, index.html, js/navbar.js
- No signout option #267 
There was no option to sign out so I added a dropdown which is shown when I click on the user greeting and hidden back when I click on user greeting.
=> Added a dropdown in user greet

js/navbar.js
Changed the navbar.js to remove the dropdown if the user clicks anywhere apart from the user greetings.
=> changed navbar.js to fix dropdown removal

README.md, css/global-variables.css, css/join.css, join.html, js/join.js
**Will be functional after https://github.com/Real-Dev-Squad/website-backend/issues/714 is closed**
**Link for the back-end PR :** https://github.com/Real-Dev-Squad/website-backend/pull/715
Once the User Signs in to Peal Dev Squad, He / She has to wait for the discord invite of the real dev squad. Currently, this process is done by Ankush through manual acquisition and takes a lot of time asking the same question to everyone who wants to join Real Dev Squad.
Create a Join section for Real dev Squad where the questions are already mentioned, and the user answers them. Once they answer all the questions, generate a personalized link for them that contains the data they entered.
- https://github.com/Real-Dev-Squad/website-www/issues/280
- …
=> Feature | join section

join.html, js/join.js
Fixed the post URL for saving join section data
closes : #295
=> Join Section | fix the post url

js/contants.js, js/github.js, js/index.js, js/user.js
how [#688](https://github.com/Real-Dev-Squad/website-backend/issues/688) will behave on the front end.
[backend PR](https://github.com/Real-Dev-Squad/website-backend/pull/694), the code for this feature.
- the webpage from which the request is initiated, its href (URL) will be passed to the request as a query param and later after authentication backend will make sure to redirect our user back to the webpage
=> new signup flow added

css/main.css, index.html, js/constants.js, js/contants.js, js/featureFlag.js, js/github.js, js/index.js, js/map.js, js/user.js, package-lock.json
- Done this
Before :
Image/Video
After :
Image/Video
**Note :**
=> Sync dev to main

js/constants.js, js/contants.js, js/github.js
- Deleted the previously created file `contants.js` and added its content to `constants.js` instead.
- Fixed imports from the previous file and now to `constants.js`
Special thanks to @RitikJaiswal75 for pointing it out.
=> file fixed

join.html, js/constants.js, js/join.js
closes #315 
This PR includes refactoring code for removing unused variables. Creating constants to ensure DRY and handling data submissions of join data.
For mode details Please refer the issue ticket #315
=> Add error handling on Preview page

js/join.js
to be merged only after: https://github.com/Real-Dev-Squad/website-backend/pull/835
The join section converts complete local storage to JSON and sends it to the backend via fetch call.
This can cause issues as some users might have some extra data in their local storage that might be sent along with the required data which is not accepted by the backend thus this PR serves the purpose to solve the issue
=> Join Section | send selected data

events.html, index.html, join.html, js/fetchUserData.js, js/index.js, releases.html
#356 
1. Removed fetchData and updateGitHubLink functions from index.js and moved them to fetchUserData.js
2. Added a new script tag in index.html, join.html, events.html, and releases.html to load fetchUserData.js with defer attribute.
After :
https://user-images.githubusercontent.com/70854507/209970229-3bcd5f8e-82a9-4a98-b7fd-9a3be69f50f8.mp4
(please ignore the video sound)
=> fix for signed in user not showing on join page 

css/join.css, join.html
#355
Fix the footer position in join.css and add class name to main tag in join.html.
Before :
After :
=> footer position fixed

events.html, js/navbar.js
#368 
1. Added sign out feature with dropdown menu in events page.
2. After adding sign out feature, the dropdown menu link is not working properly. So, I have fixed that issue also.
=> add sign out feature with dropdown in events page.

.gitignore, app/index.html, app/router.js, app/routes/join.js, app/templates/application.hbs, app/templates/join.hbs, tests/unit/routes/join-test.js
Closes #370
Created a /join route using the ember generate route <ROUTE_NAME> command.
Added a text to its hbs file.
=> [Ember-Migration] Added a /join route and initial page

.github/workflows/continuous-integration.yml
Closes #375 
Stop the CI jobs from running on Push
=> fix: workflow run test only on pull_request

css/main.css, index.html, js/index.js
#373 
- Added "How to Join Real Dev Squad" details
- Three Files have been changed index.html, main.css and index.js.
Before :
After:
https://user-images.githubusercontent.com/70854507/211705526-24700700-c526-40ec-81a8-f3f165210679.mp4
=> Add details to How to Join RDS

css/main.css, index.html, js/index.js
Following files are changed:
- `css/main.css` - Fix the description text and set text to center to anchor tag.
- `index.html` - Change button to anchor tag and add href(go to the info text section) and add id to the info text section.
- `js/index.js` - Remove unnecessary code of joinBtn button.
After :
After Request Changes
=> Fix join section

CONTRIBUTING.md
Closes #384 
Contributing.md been written with screenshots for contributing in the migration of the www-website to ember
- Created a `CONTRIBUTING.md` file.
- Added documentation for contributing in the **develop-ember**.
=> [Ember-Migration] Docs: Contributing.md

package.json
Closes #399
Added volta for node and yarn version 
- Pinned Node -> 18.12.0 (LTS)
- Pinned Yarn -> 1.22.19 (Classic Stable)
=> [Ember-Migration] Added Volta

app/components/join-steps/step-five.hbs, app/components/join-steps/step-five.js, app/router.js, app/routes/index.js, app/styles/stepper.module.css, tests/acceptance/back-to-home-button-test.js, tests/integration/components/button-test.js, tests/integration/components/step-five-test.js, tests/unit/routes/index-test.js
Closes #401
- `app/components/join-steps/step-five.hbs` - Using reusable components, create a button with text `Back to Home`
- `app/components/join-steps/step-five.js` - Use `this.router.transitionTo()` to redirect to the home page
- `app/styles/stepper.module.css` - Add styles for the button container
- `app/router.js` - Add a index route for the home page
- `app/routes/index.js` - Add a route for the home page
- `tests/unit/routes/index-test.js` - Add a test for the home page route
- `tests/integration/components/step-five-test.js` - Add a test for the button
=> [Ember-Migration] Created "Back to Home" button

app/components/join-section.hbs, app/styles/app.css, app/styles/cards.module.css, app/styles/join-section.module.css, app/styles/variables.css, app/templates/index.hbs, tests/acceptance/join-section-button-test.js, tests/integration/components/join-section-test.js
Created join-section component  just below the What is Real Dev Squad section, wrote tests for the same and added necessary media queries for the component.
Before :
After :
=> [Ember-Migration] Join section component created

app/components/footer.hbs, tests/constants/footer-data.js, tests/integration/components/footer-test.js
- Added footer component tests
Before :
Image/Video
After :
Image/Video
=> [Ember-Migration] Footer tests added

index.html
Sign inflow is not working, users get stuck after clicking on the login
Closes #413 
I removed the sign-in button as per discussion with @ankushdharkar 
Before:
After:
=> remove login button - hotfix

index.html
Add extra comments in commented code to help developers know when to enable the code
=> add comments to inform developers

css/join.css, join.html
1. `join.html` - Added "Goto Home" button in end of the join section.
2. `css/join.css` - Added css for "Goto Home" button.
https://user-images.githubusercontent.com/70854507/223294887-a5af8f1e-3c6c-43d7-9deb-a5931142aecf.mp4
=> add goto home button

index.html
- Uncommented the code for signin button in the `index.html` file
Before :
Image/Video
After :
Image/Video
=> fix : show signin button

index.html
=> Dev to main sync

js/constants.js
- Done this
Before :
Image/Video
After :
Image/Video
**Note :**
=> changed the sign up url to new signup

config/environment.js
Environment Setup for production, staging, and development 
- Added BASE_API_URL for the above mentioned environments
=> [Ember-Migration] Environment Setup

js/intro.js, js/join.js
- Did changes in two file `join.js` and `intro.js`
- change the user visible URL for join section in join.js file- `www.realdevsquad.com/intro?id=rvQTbRBHiXh8YrKiKGj4`
- change the heading of intro page in proper format
Video
https://user-images.githubusercontent.com/107163260/230616036-4d05a118-c52f-422c-9d44-d9282b3da6d4.mp4
https://user-images.githubusercontent.com/107163260/230615322-cdf551aa-5527-4d03-9e8e-abc32c9b8e9a.mp4
Video
https://user-images.githubusercontent.com/107163260/230615474-d809bdc1-3361-4bef-b787-734b6269f66a.mp4
https://user-images.githubusercontent.com/107163260/230615562-3c224980-7257-47ed-a686-29e4e0878b6d.mp4
=> change url of join.js file and heading of intro page

css/intro.css, js/intro.js
Made these change
-  Did changes into two file `intro.js` and `intro.css`
-  added numberOfHoursLabel and `numberOfHoursValue`  in intro.js
-  make first Name and last Name to Name(i.e. not separate now)
-  Now city and state Value in one line(i.e. not separate now)
- Increase the size of information input field and change line-height so that superuser not scroll for reading in mobile and desktop both
https://user-images.githubusercontent.com/107163260/231948077-71d7b55d-912f-47e0-acd7-fe9470dc095c.mp4
**Desktop View**
https://user-images.githubusercontent.com/107163260/232078445-10d009aa-c752-4c67-b94c-798d38a698e7.mp4
**Mobile View**
https://user-images.githubusercontent.com/107163260/232079165-64b33928-afd3-4dac-9f2b-cf47ed593cc6.mp4
=> render numberOfHours in intro page

js/join.js
=> resolving bug in numberOfHours field

js/join.js
Added a window.onload, so that whenever, a user hits refresh button, we can run the validation of the form again.
Before :
https://user-images.githubusercontent.com/85249044/235845751-a3a034d6-9ffc-4282-ab20-a41b39879b2e.mp4
After :
https://user-images.githubusercontent.com/85249044/235845332-d27d6e63-54e5-4818-962e-3c60afba85a2.mp4
=> Form validation not running in join section on refreshing the window

app/components/live-header.hbs, app/components/live-header.js, app/components/navbar.hbs, app/components/navbar.js, app/components/tab.hbs, app/components/tabs.hbs, app/constants/urls.js, app/controllers/live.js, app/router.js, app/styles/app.css, app/styles/live-header.module.css, app/styles/tab.module.css, app/styles/variables.css, app/templates/live.hbs, tests/acceptance/live-test.js, tests/integration/components/live-header-test.js
- Live Site changes being merged to `develop-ember` to minimize the merge and sync iterations and to avoid conflicts as well.
- From now on `live-site` development will proceed from `develop-ember` only
=> Sync develop-ember with live-site

app/components/navbar.hbs, app/components/navbar.js, app/controllers/live.js, app/routes/live.js, tests/acceptance/live-test.js, tests/unit/routes/live-test.js
Closes #474 
I have added the `dev=true` feature flag for `live-site`
**Note :**
=> [Live-Site]Added feature flag for live site

index.html, js/featureFlag.js
Remove Join Feature Flag and visible Join button.
=> Join button visible on the website

js/intro.js
- In intro.js file, added 401 image into page and alert message when user is not login.
https://github.com/Real-Dev-Squad/website-www/assets/107163260/2201405d-89e3-4ab3-8e05-02b1387903e7
=> fix intro page 

join.html
https://github.com/Real-Dev-Squad/website-www/issues/481
Fixed the social share image
=> create a social share image for realdevsquad.com/join

config/environment.js, ember-cli-build.js, package.json, yarn.lock
Closes #489
- **Added Dependencies:**
- @embroider/compat
- @embroider/core
- @embroider/webpack
- **Updated Dependencies:**
- webpack
- **Removed Dependencies:** 
- node-fetch 
- Added code splitting and tree shaking for all the routes present
- Redundant fastboot dependencies
- Redundant duplicate (empty) code block for **production** environment
https://github.com/embroider-build/embroider#readme
=> [Ember-Migration] Embroider Setup

events.html, index.html, intro.html, join.html, releases.html
- Since crypto site is down hence blocking the discovery for crypto site
Before :
Image/Video
After :
Image/Video
=> nuke: links to crypto site

app/components/join-steps/step-one.js, app/components/join-steps/step-three.js, app/components/join-steps/step-two.js, app/constants/join.js
Closes #409
I have added debounce in step one as of now.
**Note :**
=> [Ember-Migration] Implemented debounce on Inputs and Textarea of Join Section

app/constants/live.js, app/controllers/live.js, app/services/live.js, app/templates/live.hbs, config/environment.js, tests/acceptance/live-test.js
Previously we were joining the live screen share with the 100ms API. Now we are using our own Backend APIs to create and enter the room
https://github.com/Real-Dev-Squad/website-www/assets/40385118/9114a622-f2d2-4b14-8004-9a1c3772cb78
=> [Live Site] Add backend API calls

app/constants/cards-data.js, tests/constants/cards-data.js
I have removed the issue related to triple curly braces
Before :
Image/Video
After :
Image/Video
**Note :**
=> Triple Curly Lint Issue Fixed

js/user.js
Added .js extension to import constant file
=> Add .js extension to constants file

js/user.js
=> Add .js extension to constants file (#524)

app/components/join-steps/step-four.hbs, app/components/join-steps/step-four.js, app/components/join-steps/step-three.hbs, app/components/join-steps/step-three.js, app/components/stepper.hbs, tests/integration/components/step-four-test.js
- Added InputBox component with label 'How many hours per week, are you willing to contribute?' and key 'numberOfHours'.
- Added validation code for numberOfHours.
=> [Ember-Migration] Added `numberOfHours` field in Join form

app/components/navbar.js, app/constants/urls.js, config/environment.js
Closes #519 
- Fixed the login flow in staging and production
- Updated the URLs to adapt the environment
=> [Ember-Migration] Fixed redirection and updated urls

css/join.css, join.html, js/join.js
- I have added the ```dev=true``` feature flag for joining the disclaimer  before developer joining  form
- Added utils.js script file In join.js file that is missing from
Yes
https://github.com/Real-Dev-Squad/website-www/assets/86847625/477c7ebd-5fb7-478d-b18a-f22c109d354c
=> Add joining disclaimer content [feature flag]

css/navbar.css, index.html, js/user.js
Closes #535 
- Added a **.hidden** class to the `Sign in` & `Sign in with Github` buttons, which initially hides them.
- After the SELF-API call being made, based on it's success/fail the button will be shown acccordingly
- In the error case of the API-call I have targeted the two buttons from the DOM and removed the **.hidden** class on them.
- During the API call I have added Shimmer effect to avoid a Layout shift after the User Name, profile shows up.
Before :
https://github.com/Real-Dev-Squad/todo-action-items/assets/69259490/1979d11d-f858-4a10-91b5-ed57a2b36443
After :
https://github.com/Real-Dev-Squad/website-www/assets/69259490/15fc0c9e-b397-4b8c-bd9c-2a1458ab8a0e
=> FIX: Sign In Button showing up even if the user Logged In

css/navbar.css, events.html, index.html, intro.html, join.html, js/dropdown.js
This is regarding : https://github.com/Real-Dev-Squad/todo-action-items/issues/151
**OLD**
**NEW**
**RESPONSIVENESS**
https://github.com/Real-Dev-Squad/website-www/assets/85249044/9c9adfaa-5b5d-4fac-9a37-7fb867d9c21d
=> changed designs for dropdown

css/navbar.css
due to variable name crashing in join.css and navbar.css the color of dropdown items on join.css is appearing black when they should be blue
=> fixed variable name in navbar.cc

js/goto.js
- https://github.com/Real-Dev-Squad/website-my/issues/426
- https://github.com/Real-Dev-Squad/website-my/pull/435
- If user choose role **developer** on new-signup form then user will redirect to **www.realdevsquad.com/join**
- If user choose any of these role i.e. **designer, mavens, developers** on new-signup then user will redirect to **www.realdevsquad.com**
https://github.com/Real-Dev-Squad/website-www/assets/107163260/c30864f3-a572-4ab3-899f-ec3dac7add63
=> Redirection depend on roles of user

config/environment.js
fastboot giving error's as host not set
=> Add hostwhitelist for fastboot to work

__test__/index.test.js, __test__/utils.test.js, css/intro.css, js/intro.js, js/utils.js
Added red flag if  user GitHub account created within 1 year and if user Github account is more then 1 year then it'll show 
in grey color
- Make a utility function that will give you the difference between a start date and an end date. The return value will be an object with the key of years and months.
- showed message according to  GitHub created an account.
https://github.com/Real-Dev-Squad/website-backend/pull/1362
issue: It's hard, so created new ticket https://github.com/Real-Dev-Squad/website-www/issues/558
- Yes
https://github.com/Real-Dev-Squad/website-www/assets/86847625/0c9d8c6e-3cac-434d-ade3-fea03a96be83
=> feat: <1 year GitHub red flag for new joiner

package.json
Added pre-config in package.json, to run only lints on committing in local
=> Remove test on commit

package.json, yarn.lock
Add local-ssl-proxy to run on https
=> add local-ssl-proxy-for-dev

css/main.css
I tried to solve the problem when we hover on the card the animation is scaled a bit but when we leave the hover there is no animation...
Before :
https://github.com/Real-Dev-Squad/website-www/assets/80449860/9e953910-fc4f-4c4d-98b2-1ec3b7993101
After:
https://github.com/Real-Dev-Squad/website-www/assets/80449860/a1df5683-9f9a-4e65-b698-54e0e1d4771c
=> Added transition on card hover while leaving also

css/main.css, index.html, js/index.js
Closes #570 
Disabled the join button .
- Disabled join button
- Added a new line below the join button
Before :
After :
Demo Video
https://github.com/Real-Dev-Squad/website-www/assets/91171097/49b5d2a3-55f3-4514-9bb1-e59b8033649f
=> Temporarily disable join button to prevent navigation to URL

app/components/join-steps/step-one.js, app/components/join-steps/step-three.hbs, app/components/join-steps/step-three.js, app/components/join-steps/step-two.hbs, app/components/join-steps/step-two.js, app/constants/join.js, app/styles/join-section.module.css, app/styles/variables.css, app/utils/validator.js, tests/unit/utils/validator-test.js
…he functionality of word count
- Done this
Before :
Image/Video
After :
Image/Video
**Note :**
=> [Ember-Migration] Error Messages in Join Section

css/debug.css, css/navbar.css, debug.html, events.html, js/debug.js
Reverts Real-Dev-Squad/website-www#597
=> Revert "Revert "Feat: /debug page create""

js/debug.js, js/utils.js
Closes #552
**Added a /debug page where user can see :**
- basic details which he user to get after hit users/self, but in a more convenient way
- all the feature feature flags that are available to that user
- if the user is super_user he can toggle his super_user privileges as well locally
**Before**
no such page existed
After:
**Image**
**video**
https://github.com/Real-Dev-Squad/website-www/assets/49603826/7a3dbc1d-7bdc-4d95-9cf6-7ce33cfa0add
=> fix: join date format

debug.html, js/debug.js
Closes #604
- GitHub image now have a width and height 
- on debug there is greeting in the navbar is user is logged in
**Before :**
**After:**
=> Fix greeting

events.html
Closes issue ticket #623 
Previously the event page title was `upcoming events` but events which we are displaying are already happened. So changed the title to `Recap of past events` 
=> changed title of event page

.github/Issue_Ticket_Template.md
Closes #625 
Setup the issue ticket template for a contributor for better contributing experience.
=> issue ticket template add

index.html
- Done this
Before :
Image/Video
After :
Image/Video
**Note :**
=> Change join section text

__test__/index.test.js, jest.config.js
- Closes #632 
- Update the test Environment to the node in jest config as it is necessary for the puppeteer to run tests in a browser-like environment.
- On index.test.js: Fixed page not defined error caused due to missing import of puppeteer which provides page instance required
- [-] Yes
Before :
After :
=> Issue 632/fix: Fix the "Module not defined" error thrown while running test

app/components/reusables/onboarding-input.hbs
- resolve esLint error in our codebase related to binding to a down event.
=> Ignore ESLint Error for Binding to down Event

app/components/signup-steps/step-zero.hbs, app/styles/footer.module.css, app/styles/onboarding-card.module.css, app/styles/stepper.module.css
#647 
Parent ticket: https://github.com/Real-Dev-Squad/todo-action-items/issues/178
**Description**
Fix CSS for different media queries for signup steps
https://github.com/Real-Dev-Squad/website-www/assets/111434418/742cbe10-4f18-41e8-a806-2b8097265d66
=> Fix design in signup steps

app/components/live-join.hbs, app/components/live-participants.hbs, app/styles/live-header.module.css, app/styles/live-join.module.css, app/styles/live-sidebar.module.css, app/styles/live.module.css, app/styles/variables.css, app/templates/live.hbs
Done styling changes to improve the UI/UX of live-site, below are the changes that is being done :
-  Min width for main container so when loading state gets true the screen doesn't get shrinked.
-  Hide kickout button for self (like moderator can't kick the mods and also can't kick themselves too). Similarly for other peers, if any.
-  Highlight if the peer name is local user
-  Add coming soon notification for previous events and open link on click on Realdevsquad in top panel component
https://github.com/Real-Dev-Squad/website-www/assets/85296770/84e953f2-204d-4038-93fc-48deb1691623
=> [Live-Site] Refactor/live site stylings

app/components/live-sidebar.hbs, app/constants/urls.js, app/services/live.js, tests/integration/components/live-participants-test.js
=> [Live-Site]- Rendering for a host in sidebar as per other roles.

app/components/signup-steps/step-one.hbs, app/components/signup-steps/step-two.hbs, app/components/signup-steps/step-zero.hbs, app/components/stepper-signup.hbs, app/styles/onboarding-card.module.css, tests/integration/components/signup-steps/step-two-test.js
Closes #660 
https://github.com/Real-Dev-Squad/website-www/assets/111434418/6904b4d7-05f5-4dbb-9617-c0013a2f251e
=> Getting started page

package.json
=> add staging command

app/components/live-sidebar.hbs, app/components/video-screen.hbs, app/components/video-screen.js, app/services/live.js, app/styles/app.css, app/styles/live-header.module.css, app/styles/live-sidebar.module.css, app/styles/live.module.css, app/styles/video-screen.module.css, app/templates/live.hbs, tests/integration/components/live-sidebar-test.js
This PR fixes the following bugs : 
**Note :**
=> [Live-Site] : Fix/UI bugs

app/components/identity-steps/step-four.hbs, app/components/identity-steps/step-four.js, app/components/stepper-signup.hbs, app/styles/onboarding-card.module.css, tests/integration/components/identity-steps/step-four-test.js, tests/integration/components/input-box-test.js
Parent Ticket: https://github.com/Real-Dev-Squad/todo-action-items/issues/178
- added heading and description and write test for it.
- added generate chaincode button which clicked then a div with text and two icon (eye+copy) render
- feature under feature flag
https://github.com/Real-Dev-Squad/website-www/assets/107163260/38b9faa2-e988-4dab-a1d5-069629117952
Test
https://github.com/Real-Dev-Squad/website-www/assets/107163260/b1810b93-0620-40fb-a10c-59275c0b8014
=> [Onboarding Flow]- Chaincode Generation Page in Identity Service Setup

app/components/identity-steps/step-one.hbs, app/components/identity-steps/step-three.hbs, app/components/identity-steps/step-two.hbs, app/components/stepper-signup.hbs, tests/integration/components/identity-steps/step-one-test.js, tests/integration/components/identity-steps/step-three-test.js, tests/integration/components/identity-steps/step-two-test.js
parent ticket: https://github.com/Real-Dev-Squad/todo-action-items/issues/178
Added challenges steps for the developer after filling the join form 
https://github.com/Real-Dev-Squad/website-www/assets/111434418/ff102eed-9ead-4836-b584-0dc12d847e2c
=> Identity service challenge steps

js/constants.js, js/goto.js
[https://github.com/Real-Dev-Squad/website-www/issues/645](https://github.com/Real-Dev-Squad/website-www/issues/645)
Changed the goto.js file which is responsible to redirect the new user to the signup form.
- Done this
https://github.com/Real-Dev-Squad/website-www/assets/55151241/5b42f3df-50b3-4cf6-a175-ec11e66cc849
=> Redirect the new user to welcome page

app/components/identity-steps/step-five.hbs, app/components/identity-steps/step-five.js, app/components/identity-steps/step-four.hbs, app/components/identity-steps/step-four.js, app/components/reusables/button.hbs, app/components/stepper-signup.hbs, app/components/stepper-signup.js, app/styles/button.module.css, app/styles/onboarding-card.module.css, app/utils/check-url.js, tests/integration/components/identity-steps/step-five-test.js, tests/integration/components/identity-steps/step-four-test.js, tests/unit/utils/check-url-test.js
- Now chaincode generate from backend i.e. chaincode fetched from backend
- Modify styling of chaincode generation page
- due to MSW is not setup in website-www branch develop-ember repo because of that I have to skip some test of chancode generation page which run before in https://github.com/Real-Dev-Squad/website-www/pull/676
- Make profile service url page in which it contain  heading, description, input field, tooltip and button 
- next button on  profile service url page only enable when input contain valid url 
- When user click next button then data stored in backend.
- I have written utils function-checkURL which check url on profile-page input field is valid or not
- You find test for every functionality i implemented on profile-page
- Feature under feature flag
**After change …
=> [Onboarding Flow] - Profile Service Setup and Linking with Identity Service

index.html
Properly Disable Join Link #688
Provide a small description in points of what did you change :   We aren't currently accepting new join applications. The link to join RDS is currently disabled by using pointer-events: none, which can be easily overridden from browser devtools and then click on the link. The joining page link is also available in devtools inspect html, which can also be clicked to go to join form. so for solving this we will replace the value of href.
<h1>WHAT IS THE CHANGE :</h1>  removing the value of href from join button give below for dissable join button 
- Done this
After change image :+1: 
<h3>Test Stats:</h3> 
<p> Beforre</p>
<p> After</p>
=> join dissable button

app/components/events/logs-page.hbs, app/components/events/logs-page.js, app/controllers/live.js, app/styles/app.css, app/styles/logs-page.module.css, app/templates/live.hbs, tests/integration/components/events/logs-page-test.js
- #707
In this PR I have created UI for the events logs page in live-site. The API integration will be done separately in next ticket.
> Desktop Version
> Tab Version
> Mobile Version
- API integration for this ticket to be done separately by ticket #706
- Added some dummy data which will be removed when the API will be integrating, ensuring the clean code.
=> [Live-Site] Created UI for event logs feature

app/components/kickout-modal.hbs, app/components/kickout-modal.js, app/components/live-panel.hbs, app/controllers/live.js, app/styles/kickout-modal.module.css, app/templates/live.hbs, tests/integration/components/live-panel-test.js
Added warning modal before the host ends the event.
https://github.com/Real-Dev-Squad/website-www/assets/40385118/a587f6a9-2b70-455e-8fe5-15e619c5ebc3
https://github.com/Real-Dev-Squad/website-www/assets/40385118/b10c69c1-8f66-4f94-8914-4a17ba1586bf
=> [Live-Site] Add warning modal before event end

app/components/events.hbs, app/components/events.js, app/components/footer.hbs, app/components/footer.js, app/constants/events-data.js, app/styles/app.css, app/styles/events.module.css, app/styles/footer.module.css, app/styles/variables.css, app/templates/index.hbs, tests/acceptance/migration-changes-under-feature-flag-test.js, tests/constants/events-data.js, tests/integration/components/events-test.js
Closes #708 
- #708 
- Synced beta site footer with vanilla site footer
- Added events section in beta site
- Added tests for migration changes under `?dev=true` feature flag
Before: 
After:
https://github.com/Real-Dev-Squad/website-www/assets/87164140/89418a2a-61e7-4969-9aa1-d4a908045298
https://github.com/Real-Dev-Squad/website-www/assets/87164140/6eea0bb1-16fe-4d86-bf39-bbeeb1fa817b
The changes are under `?dev=true` feature flag.
The feature flag should be removed from these changes after migration changes are confirmed.
=> [Ember Migration] Footer Changes

app/components/identity-steps/step-four.hbs, app/components/identity-steps/step-four.js, app/components/stepper-signup.hbs, app/controllers/join.js, app/templates/join.hbs, tests/integration/components/identity-steps/step-four-test.js
- Before fetching an API in an component, but Now I moved it to the controller file
- Fix all the test and skip test
- under feature flag
https://github.com/Real-Dev-Squad/website-www/assets/107163260/63ed8190-d72e-43fb-9a3d-a68b83982d99
https://github.com/Real-Dev-Squad/website-www/assets/107163260/88215f45-cce8-4515-a7c2-b215840c99c2
=> [Onboarding Flow]- Write test after the "Generate Chaincode" button is clicked 

app/components/navbar.hbs, app/components/navbar.js, app/constants/urls.js, app/controllers/application.js, app/templates/application.hbs, tests/constants/urls.js, tests/integration/components/navbar-test.js
- fix Navbar dropdown like other site
- Change in file `app/components/navbar.hbs`, 
- Added link of each item of dropdown
- Link will open in new tab
- Uses feature flag from service file
- Written Test
https://github.com/Real-Dev-Squad/website-www/assets/107163260/290f0a55-55bb-4025-8119-8f54be9cf46a
https://github.com/Real-Dev-Squad/website-www/assets/107163260/2bca5aec-a26a-4544-8f98-581d6c34310a
=> Navbar fix with dropdown 

app/components/description.hbs, app/controllers/index.js, app/styles/description.module.css, app/templates/index.hbs, tests/acceptance/migration-changes-under-feature-flag-test.js, tests/unit/controllers/index-test.js
In this PR I have created what is RealDevSquad section.
Date: 9-11-2023
Developer Name: Satyam Bajpai
PR Number(s):- #741
Issue Ticket Number:-  #740 
Backend changes
Frontend Changes
Is Under Feature Flag 
Deployment notes
Any special instructions for the deployment (N/A)
Tested in staging
https://github.com/Real-Dev-Squad/website-www/assets/85296770/0a900b8f-b70d-4216-9a1e-552beb5a6e8f
> Tests Snapshot
**Note :**
=> [Ember-Migration] Created "what is RealDevSquad section"

app/styles/cards.module.css, app/styles/live-join.module.css, app/styles/live-roles.module.css
fixes #697 
Changed width of `Join the Event` card on small screen
=> [Live-Site] Fix role choose card width 

.github/Pull_Request_Template.md
Updated the pull request template of develop-ember branch.
- Done this
Before :
Image/Video
After :
Image/Video
**Note :**
=> updated pull request template

app/components/scroll-to-top.js
closes #767 
While starting the server an error is coming related to type error while using fast boot
- apply if condition for checking no fastboot
For visual or interaction changes. Please provide a video/screenshot.
Before :
After :
**Note :**
=> [Bug] fastboot error

app/index.html
Added Google and Posthog analytics to get analytics of our web app.
n/a
**Note :**
=> feat: add google and posthog analytics

app/components/header.hbs, app/constants/urls.js, tests/integration/components/header-test.js
Hide events page, and URL link 
Before :
After :
=> Hide events page

README.md
Update README.md, fix spelling mistakes
=> Update README.md, fix spelling mistakes

app/services/login.js
Date: `04-01-2024`
Developer Name: `vinit`
---
Refactor the auth redirection condition to not check in dev mode
=> Refactor auth redirection in dev mode

public/.well-known/assetLinks.json
Date: `6-jan-2024`
Developer Name: `shreya`
---
- broken change
Why do we need this?
We are implementing SignIn with github in mobile so we need the deeplink to be implemented in website for the redirect back to mobile app.
What is the change?
Added assetlinks.json file for mobile app verification and redirecting it to mobile app from new signUp flow site in case of signInwith github login from mobile.
=> added asset-link file for deeplinking

app/components/signup-steps/step-one.js
Update firstname, lastname, usrname on username generation
=> Update firstname, lastname, usrname on username generation

app/components/identity-steps/step-five.hbs, app/components/identity-steps/step-four.hbs, app/components/identity-steps/step-four.js, app/components/tooltip.hbs, app/constants/urls.js, app/services/onboarding.js, app/styles/app.css, app/styles/onboarding-card.module.css, app/styles/stepper.module.css, app/styles/tooltip.module.css, app/templates/join.hbs, tests/integration/components/identity-steps/step-five-test.js
Date: `07-01-2024`
---
- closes #828
=> feat: add tooltip in indentity code copy step

app/components/join-steps/status-card.hbs, app/components/join-steps/status-card.js, app/components/signup-steps/step-one.hbs, app/components/signup-steps/step-one.js, app/constants/stepper-signup-data.js, app/constants/urls.js, tests/integration/components/signup-steps/step-one-test.js
=> fix: join steps

app/constants/urls.js
=> chore: change url of backend

app/components/live-header.hbs, app/components/live-header.js, app/controllers/live.js
Date: `24-01-2024`
---
- #848 
- #850 
=> SYNC: develop to main

app/components/debug-grids.hbs, app/components/debug-grids.js, app/components/unauthenticated.hbs, app/models/user.js, app/router.js, app/routes/debug.js, app/styles/app.css, app/styles/debug.module.css, app/styles/unauthenticated.module.css, app/styles/variables.css, app/templates/debug.hbs, app/utils/common-utils.js, tests/integration/components/debug-grids-test.js, tests/integration/components/unauthenticated-test.js, tests/unit/routes/debug-test.js
Commits: 
* setup:basic-debug-page
* styles:tidy us styles
* feat/debug-page-functionalities
* add box-shadow
* add fallback image
* add basic modal
* change modifier syntax
* remove console log
* skip test for current pr
* responsive design
* max-width on bigger screens
* add feature flag to debug page
* add user data load error response
* using async-await for data fetching
* update property name
* chore:update function name
* remove unnecessary toast message
* resolve comments related to css
* refactor: use login service for user data
* style: update BEM convention
* style: update classnames - BEM convention
* feat: improved unauthenticated message
Date: 6th Feb 2024
Developer Name: @ajoykumardas12 
---
- #738 
This PR syncs changes for debug page to develop branch.
Is Under Feature …
=> [Ember Migration] Debug Page (#852)

app/components/debug-grids.js
Date: 7th Feb 2024
Developer Name: @ajoykumardas12 
---
- #738 
This PR adds a fix for main PR: #852 
=> Properly Handle Unavailable Property

app/components/debug-grids.js, app/models/user.js
Date: 7th Feb 2024
Developer Name: @ajoykumardas12 
---
- #738 
This PR contains a fix for main PR: #852 
=> Fix Incorrect Property For Discord Id

app/constants/live.js, app/styles/live-roles.module.css
Date: 08 February 2024
Developer Name: @Achintya-Chatterjee 
---
- https://github.com/Real-Dev-Squad/website-www/issues/859
Till now the the role buttons was small case and this is not right UX for the end User. I changes  the first letter of the role buttons names to camel case.
Is Under the Feature Flag
Tested in Local?
[Screencast from 08-02-24 03:54:13 PM IST.webm](https://github.com/Real-Dev-Squad/website-www/assets/55826451/7c2c015a-f8b0-426e-8751-73081ea3d7bb)
=> [Live-Site] Capital casing added for Role Button

app/controllers/live.js
Date: Feb 14 2024
Developer Name: Jayasurya
---
Issue #860
=> fix: add loading text to button when no data

app/controllers/live.js, tests/integration/components/live-join-test.js
Date: 16 Feb 2024
Developer Name: Jayasurya
---
#865 
Prefill first name of user in events input field
=> Feat: prefill first name in input for events

app/components/join-section.hbs, app/components/stepper.js
Date: `27-02-2024`
---
- #876
Add toast for "applications currently not accepting information" and not call the join API.
=> fix: add toast for applications currently not accepting information and not call the API

app/styles/cards.module.css
Date: 19th April 2024
Developer Name: Palak Gupta
---
closes #883 
Currently in  `Why you should consider joining?` section, if we click on the cards, the modal opens up abruptly, 
to improve that experience, added animation in the modal pop-up, to smooth the transition.
[cuurent.webm](https://github.com/Real-Dev-Squad/website-www/assets/61227144/3e6d8ba8-493d-4eaa-8459-2c9ef4efd6b9)
https://github.com/Real-Dev-Squad/website-www/assets/61227144/365b51ce-1fb0-4df8-9b61-16251f40ca01
=> improve upon transition for modal up in Why you should consider joining? section

app/components/stepper.js, app/templates/join.hbs
Based on approved PR https://github.com/Real-Dev-Squad/website-www/pull/896 ✅
=> Hotfix: 895 archived users unable to use join

app/styles/app.css, app/styles/feedback.css, app/templates/intro.hbs
- #900 
- fix superuser feedback input styling
- remove unused checks in intro template
=> fix super user feedback text area styling

app/components/join-steps/status-card.hbs, app/components/join-steps/status-card.js, app/components/stepper.hbs, app/components/stepper.js, app/constants/apis.js, app/constants/stepper-data.js, app/constants/urls.js, app/services/onboarding.js, app/styles/status-card.module.css, tests/integration/components/status-card-test.js, tests/integration/components/stepper-test.js
Date: `19-08-2024`
Developer Name: `vinit`
---
- closes #903 
Add a status card and based on the application user we have shown to the user and if the application goes approved then we have to give discord invite link 
=> Enhance Status Page with Application Status, Feedback, and Discord Invite Link

app/controllers/join.js, app/routes/join.js, app/services/onboarding.js, app/styles/join-section.module.css, app/templates/join.hbs, tests/unit/controllers/join-test.js
=> Add login message when not logged in users visit /join

app/routes/debug.js, tests/unit/routes/debug-test.js
Date: `19th Sep 2023`
Developer Name: `Shubham Raj`
---
Add the /debug page under feature until testing
[Screencast from 19-09-24 03:39:14 PM IST.webm](https://github.com/user-attachments/assets/a2c6d16f-2475-459a-ad95-15a4f567c751)
[Screencast from 19-09-24 03:44:52 PM IST.webm](https://github.com/user-attachments/assets/8f2fa638-4534-43a3-abe4-0398deadc128)
=> Puts /debug page behind ff for testing before removing it

app/components/header.hbs, app/components/join-section.hbs, app/constants/regex.js, app/constants/urls.js, app/controllers/subscribe.js, app/models/user.js, app/router.js, app/routes/subscribe.js, app/styles/app.css, app/styles/base-modal.module.css, app/styles/join-section.module.css, app/styles/phone-input.module.css, app/styles/subscribe.module.css, app/templates/subscribe.hbs, config/environment.js, package.json, yarn.lock
Date: 24 oct, 2024
---
- [link](https://github.com/Real-Dev-Squad/website-backend/issues/2123)
- this PR introduces the subscription feature, in which we are collecting user emails and phone numbers to send them notifications in the future.
- [] No
https://github.com/user-attachments/assets/ee030acd-f6db-42cc-8139-62a1c74d6b3b
and stacked test cases PR: https://github.com/Real-Dev-Squad/website-www/pull/945
=> Dev to Main (Subscription Feature)

app/routes/debug.js, tests/unit/routes/debug-test.js
Date: `23 Oct 2024`
Developer Name: `Shubham Raj`
- Closes #947 
This PR removes the /debug page from behind the dev feature flag
https://github.com/user-attachments/assets/d5b18936-4c45-4f16-94b3-86163a2de3df
=> remove /debug page from dev feature flag

app/constants/apis.js, app/router.js, app/routes/mobile.js, app/templates/mobile.hbs, tests/unit/routes/mobile-test.js
Date: 11-02-2025
---
Closes #593 
Mobile verification page is being moved from my-site to main-site at `/mobile` route.
This PR moves only the mobile route and contains unit tests for the same and a basic mobile template with no content yet.
`/mobile` is under feature flag and can only be accessed with `dev=true`
<details>
<summary>Demo video</summary>
https://github.com/user-attachments/assets/e7d9175d-cede-41c6-8bcb-94423fe0a99e
https://github.com/user-attachments/assets/0dc7222d-a4bc-40bd-a153-0b2262a507b6
</details>
<details>
<summary>Tests</summary> 
</details>
=> [My Site Migration] mobile verification page (Part - 1)

app/components/user-status.js, app/constants/apis.js, app/constants/user-status.js, app/controllers/status.js, app/routes/status.js, tests/integration/components/user-status-test.js, tests/unit/controllers/status-test.js, tests/unit/routes/status-test.js
Date: 13-03-2025
---
- #590 
This is a refactor PR for user status functionality. The PR contains the following improvements: 
- Naming for `cancelOOOStatus` has now been updated to `cancelOoo` for request payload.
- Using constants for error messages and API Urls in status route
<details>
<summary>Demo</summary>
https://github.com/user-attachments/assets/4e8744d0-b32b-4ef6-9534-80314f0b632c
</details>
<details>
<summary>Tests</summary>
</details>
=> Refactor: status route for user status functionality

app/constants/new-signup.js, app/constants/urls.js, app/router.js, app/routes/new-signup.js, app/templates/new-signup.hbs, tests/unit/routes/new-signup-test.js
Date: 14-04-25
Developer Name: @MayankBansal12
---
- #1021 
(Doesn't closes the issue, it's Part-1 for changes)
- `New-Signup` page is being migrated from my-site to main-site.
- This PR contains `new-signup` route and its unit tests along with a default template `new-signup.hbs` to be followed by migrating `new-signup` controller, components, and style changes in the next PR.
<details>
<summary>Demo</summary>
https://github.com/user-attachments/assets/8b0bcf6b-3352-4efb-9617-4d78bd497eb6
</details>
<details>
<summary>Tests</summary>
</details>
=> [My Site Migration] new-signup page (Part - 1 -  route)

app/controllers/identity.js, app/templates/identity.hbs
Date: 23-04-2025
---
- Closes #1041
- The PR fixes a bug in the identity page, while clicking on get started the page won't move to step1. The issue was due to `this.state` not being handled properly.
<details>
<summary>Screencast</summary>
https://github.com/user-attachments/assets/17e1a939-657b-4c89-865c-6ae73d10d447
</details>
=> fix: get-started bug in identity page

app/components/new-signup/checkbox.hbs, app/components/new-signup/checkbox.js, app/components/new-signup/info.hbs, app/components/new-signup/info.js, app/components/new-signup/input.hbs, app/components/new-signup/input.js, app/styles/app.css, app/styles/new-signup.module.css, app/styles/variables.css, app/templates/new-signup.hbs
Date: 21-04-2025
---
- closes #1021
- `New-Signup` page is being migrated from `my-site` to `main-site`.
- This PR contains components and styling additions for new-signup page
- Integration tests for the components are included in PR #1038 
<details>
<summary>Screenshots and demo</summary>
https://github.com/user-attachments/assets/ef963a69-9f06-4150-b6fd-8f7ced13d506
<details>
<summary>Mobile responsiveness</summary>
https://github.com/user-attachments/assets/42c365f1-8a76-45a8-858f-b5aa5328af39
</details>
<details>
<summary>under signup dev</summary> …
=> [My Site Migration] new-signup page (Part - 3 - styling and components)

app/components/user-status-modal.hbs, app/components/user-status-modal.js, app/constants/apis.js, app/constants/user-status.js, app/controllers/status.js, app/templates/status.hbs, tests/integration/components/user-status-modal-test.js, tests/unit/controllers/status-test.js
Date: 13-09-2025
---
- closes #1071 
- Updates fields in request body for creating OOO requests under dev mode
- Add unit tests for create OOO req in dev flag
<details>
<summary>success case</summary>
https://github.com/user-attachments/assets/5b18caa2-62f0-4213-a4c7-8bc75bd11e6b
</details>
<details>
<summary>error case</summary>
https://github.com/user-attachments/assets/10925249-6d78-4b4a-b759-80a819bf0f1b
</details>
<details>
<summary>tests</summary>
note:  6 tests were already skipped in repo
</details>
Update the request logic to use a new endpoint and function for creating OOO …
=> fix: update request body for create ooo requests in dev mode
